namespace NAFServer.src.Domain.Enums
{
    public enum Progress
    {
        OPEN, // NO APPROVERS YET
        IN_PROGRESS, // AN APPROVER APPROVED THE REQUEST AND NOW WAITING FOR THE NEXT APPROVER/S
        REJECTED, // AN APPROVER REJECTED THE REQUEST
        FOR_SCREENING, // ALL APPROVERS APPROVED THE REQUEST AND THE TECHNICAL TEAM WILL PROCEED WITH THE PREPARATION
        ACCOMPLISHED, // ALL APPROVERS APPROVED THE REQUEST AND THE TECHNICAL TEAM DELIVERED THE REQUEST
        NOT_ACCOMPLISHED // THE REQUEST IS REJECTED AND THE REQUESTOR CLOSED THE REQUEST
    }
}
