namespace NAFServer.src.Domain.Enums
{
    public enum Progress
    {
        OPEN, // NO APPROVERS YET
        IN_PROGRESS, // AN APPROVER APPROVED THE REQUEST AND NOW WAITING FOR THE NEXT APPROVER/S
        REJECTED, // AN APPROVER REJECTED THE REQUEST
        IMPLEMENTATION, // ALL APPROVERS APPROVED THE REQUEST AND NOW THE TECHNICAL TEAM IS WORKING ON THE REQUEST
        ACCOMPLISHED, // ALL APPROVERS APPROVED THE REQUEST AND THE TECHNICAL TEAM DELIVERED THE REQUEST
        NOT_ACCOMPLISHED // THE REQUEST IS REJECTED AND THE REQUESTOR CLOSED THE REQUEST
    }
}
