// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NAFServer.src.Infrastructure.Persistence;

#nullable disable

namespace NAFServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ApprovalWorkflowStepsTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ApprovalWorkflowTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApproverEntity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApproverRole")
                        .HasColumnType("int");

                    b.Property<int>("StepAction")
                        .HasColumnType("int");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalWorkflowTemplateId");

                    b.ToTable("ApprovalWorkflowStepsTemplates");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ApprovalWorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("ApprovalWorkflowTemplates");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.Department", b =>
                {
                    b.Property<string>("DepartmentDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentHeadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.Employee", b =>
                {
                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentHeadId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiredDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegularizedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeparatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.GroupEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GroupEmails");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.InternetPurpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InternetPurposes");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.InternetResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurposeId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PurposeId");

                    b.ToTable("InternetResources");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.NAF", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("AccomplishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NAFs");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ResourceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("AccomplishedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ApprovalWorkflowTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("NAFId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalWorkflowTemplateId");

                    b.HasIndex("NAFId");

                    b.HasIndex("ResourceId");

                    b.ToTable("ResourceRequests");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ResourceRequestApprovalStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<Guid>("ResourceRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceRequestId");

                    b.ToTable("ResourceRequestApprovalSteps");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ResourceRequestApprovalStepHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForRejection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResourceRequestApprovalStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceRequestApprovalStepId");

                    b.ToTable("ResourceRequestApprovalStepHistories");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ResourceRequestImplementation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AccomplishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DelayReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DelayedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResourceRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResourceRequestId")
                        .IsUnique();

                    b.ToTable("Implementations");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ResourceRequestPurpose", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("ResourceRequestApprovalStepHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResourceRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResourceRequestApprovalStepHistoryId");

                    b.HasIndex("ResourceRequestId");

                    b.ToTable("ResourceRequestPurposes");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.SharedFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SharedFolders");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Interface.ResourceRequestAdditionalInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AdditionalInfoType")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<Guid>("ResourceRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResourceRequestId")
                        .IsUnique();

                    b.ToTable("AdditionalInfo");

                    b.HasDiscriminator<string>("AdditionalInfoType").HasValue("ResourceRequestAdditionalInfo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.GroupEmailRequestInfo", b =>
                {
                    b.HasBaseType("NAFServer.src.Domain.Interface.ResourceRequestAdditionalInfo");

                    b.Property<int>("GroupEmailId")
                        .HasColumnType("int");

                    b.HasIndex("GroupEmailId");

                    b.HasDiscriminator().HasValue("GroupEmail");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.InternetRequestInfo", b =>
                {
                    b.HasBaseType("NAFServer.src.Domain.Interface.ResourceRequestAdditionalInfo");

                    b.Property<int>("InternetResourceId")
                        .HasColumnType("int");

                    b.HasIndex("InternetResourceId");

                    b.HasDiscriminator().HasValue("Internet");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.SharedFolderRequestInfo", b =>
                {
                    b.HasBaseType("NAFServer.src.Domain.Interface.ResourceRequestAdditionalInfo");

                    b.Property<int>("SharedFolderId")
                        .HasColumnType("int");

                    b.HasIndex("SharedFolderId");

                    b.HasDiscriminator().HasValue("SharedFolder");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ApprovalWorkflowStepsTemplate", b =>
                {
                    b.HasOne("NAFServer.src.Domain.Entities.ApprovalWorkflowTemplate", "ApprovalWorkflowTemplate")
                        .WithMany()
                        .HasForeignKey("ApprovalWorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflowTemplate");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ApprovalWorkflowTemplate", b =>
                {
                    b.HasOne("NAFServer.src.Domain.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.InternetResource", b =>
                {
                    b.HasOne("NAFServer.src.Domain.Entities.InternetPurpose", "Purpose")
                        .WithMany()
                        .HasForeignKey("PurposeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purpose");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ResourceRequest", b =>
                {
                    b.HasOne("NAFServer.src.Domain.Entities.ApprovalWorkflowTemplate", "ApprovalWorkflowTemplate")
                        .WithMany("ResourceRequests")
                        .HasForeignKey("ApprovalWorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NAFServer.src.Domain.Entities.NAF", "NAF")
                        .WithMany("ResourceRequests")
                        .HasForeignKey("NAFId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NAFServer.src.Domain.Entities.Resource", "Resource")
                        .WithMany("ResourceRequests")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflowTemplate");

                    b.Navigation("NAF");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ResourceRequestApprovalStep", b =>
                {
                    b.HasOne("NAFServer.src.Domain.Entities.ResourceRequest", "ResourceRequest")
                        .WithMany("ResourceRequestsApprovalSteps")
                        .HasForeignKey("ResourceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResourceRequest");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ResourceRequestApprovalStepHistory", b =>
                {
                    b.HasOne("NAFServer.src.Domain.Entities.ResourceRequestApprovalStep", "ResourceRequestApprovalStep")
                        .WithMany("Histories")
                        .HasForeignKey("ResourceRequestApprovalStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceRequestApprovalStep");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ResourceRequestImplementation", b =>
                {
                    b.HasOne("NAFServer.src.Domain.Entities.ResourceRequest", "ResourceRequest")
                        .WithOne("ResourceRequestImplementation")
                        .HasForeignKey("NAFServer.src.Domain.Entities.ResourceRequestImplementation", "ResourceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceRequest");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ResourceRequestPurpose", b =>
                {
                    b.HasOne("NAFServer.src.Domain.Entities.ResourceRequestApprovalStepHistory", "ResourceRequestApprovalStepHistory")
                        .WithMany()
                        .HasForeignKey("ResourceRequestApprovalStepHistoryId");

                    b.HasOne("NAFServer.src.Domain.Entities.ResourceRequest", "ResourceRequest")
                        .WithMany("ResourceRequestPurposes")
                        .HasForeignKey("ResourceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceRequest");

                    b.Navigation("ResourceRequestApprovalStepHistory");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Interface.ResourceRequestAdditionalInfo", b =>
                {
                    b.HasOne("NAFServer.src.Domain.Entities.ResourceRequest", "ResourceRequest")
                        .WithOne("AdditionalInfo")
                        .HasForeignKey("NAFServer.src.Domain.Interface.ResourceRequestAdditionalInfo", "ResourceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceRequest");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.GroupEmailRequestInfo", b =>
                {
                    b.HasOne("NAFServer.src.Domain.Entities.GroupEmail", "GroupEmail")
                        .WithMany()
                        .HasForeignKey("GroupEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupEmail");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.InternetRequestInfo", b =>
                {
                    b.HasOne("NAFServer.src.Domain.Entities.InternetResource", "InternetResource")
                        .WithMany()
                        .HasForeignKey("InternetResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InternetResource");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.SharedFolderRequestInfo", b =>
                {
                    b.HasOne("NAFServer.src.Domain.Entities.SharedFolder", "SharedFolder")
                        .WithMany()
                        .HasForeignKey("SharedFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SharedFolder");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ApprovalWorkflowTemplate", b =>
                {
                    b.Navigation("ResourceRequests");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.NAF", b =>
                {
                    b.Navigation("ResourceRequests");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.Resource", b =>
                {
                    b.Navigation("ResourceRequests");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ResourceRequest", b =>
                {
                    b.Navigation("AdditionalInfo")
                        .IsRequired();

                    b.Navigation("ResourceRequestImplementation")
                        .IsRequired();

                    b.Navigation("ResourceRequestPurposes");

                    b.Navigation("ResourceRequestsApprovalSteps");
                });

            modelBuilder.Entity("NAFServer.src.Domain.Entities.ResourceRequestApprovalStep", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
